services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "TodoList"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d TodoList"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  backend-todo:
    image: todo-backend
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always

  client-todo:
    image: todo-client
    build:
      context: ./todo-client
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    restart: always