version: "3.9"
services:
  main:
    container_name: TodoBackend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}:${PORT}
    command: yarn start:dev
    depends_on:
      - postgres
    restart: always
    stdin_open: true
    tty: true

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d TodoList"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

